[project]
name = 'Tokenized-Healthcare-Medication-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.patient-verification]
path = 'contracts/patient-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.prescriber-verification]
path = 'contracts/prescriber-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
